/* soapClient.c
   Generated by gSOAP 2.8.78 for trabajo.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.78 2019-02-05 22:00:01 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__testParser(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *desc, char *info, struct getParserResponse *r)
{	if (soap_send_ns__testParser(soap, soap_endpoint, soap_action, id, desc, info) || soap_recv_ns__testParser(soap, r))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__testParser(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *desc, char *info)
{	struct ns__testParser soap_tmp_ns__testParser;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/trabajo";
	soap_tmp_ns__testParser.id = id;
	soap_tmp_ns__testParser.desc = desc;
	soap_tmp_ns__testParser.info = info;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns__testParser(soap, &soap_tmp_ns__testParser);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__testParser(soap, &soap_tmp_ns__testParser, "ns:testParser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__testParser(soap, &soap_tmp_ns__testParser, "ns:testParser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__testParser(struct soap *soap, struct getParserResponse *r)
{
	struct ns__testParserResponse *soap_tmp_ns__testParserResponse;
	if (!r)
		return soap_closesock(soap);
	soap_default_getParserResponse(soap, r);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__testParserResponse = soap_get_ns__testParserResponse(soap, NULL, "ns:testParserResponse", NULL);
	if (!soap_tmp_ns__testParserResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (r && soap_tmp_ns__testParserResponse->r)
		*r = *soap_tmp_ns__testParserResponse->r;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
